### PR TITLE
Upgrade WebdriverIO to v7

### PR DESCRIPTION
**Pull request by sahilgrewal8072**
@wiese @Ladsgroup @jakobw @tarrow Hi ! I am Sahil Grewal , currently a student developer @wikimedia as part of GSoC'21. This PR is a part of my project regarding upgrading all the repositories from v6 to v7, Please refer here for more info : [T274579](https://phabricator.wikimedia.org/T274579) 

I have made all the necessary changes for upgrading purpose. It would be great if you could review this PR.

### CODE REVIEW

**Comment by sahilgrewal8072** [comment]
@zeljkofilipin Checkout this once you feel free!

**Comment by vidhi-mody** [comment]
@micgro42 @wiese @lucaswerkmeister @tarrow @Ladsgroup 
Hi! I am mentoring @sahilgrewal8072 for the project [Upgrade WebdriverIO to the latest version 7 for all repositories](https://phabricator.wikimedia.org/T274579) as a part of Google Summer of Code 2021. It would be great if you could review this PR. Thanks!

**Comment by micgro42** [comment]
I'm having a look now

**Review by micgro42 — APPROVED** [review]
I'm not really able to try it out locally, but from reading the documentation about this update, it _should_ be fine. Nothing described here should affect us: https://webdriver.io/blog/2021/02/09/webdriverio-v7-released/

**Comment by vidhi-mody** [comment]
🥳🥳🥳

**Comment by micgro42** [comment]
For coordination purposes and to prevent duplicate work: Are you going to make a new release of this library and update it in the places where it is used, or should we take that over?

**Comment by sahilgrewal8072** [comment]
As GSoC'21 period is about to end ... I am not sure I would be able to make this...So yes ! you can take over on this

**Comment by micgro42** [comment]
> As GSoC'21 period is about to end ... I am not sure I would be able to make this...So yes ! you can take over on this

:+1:

:point_right: [:anchor:T288443](https://phabricator.wikimedia.org/T288443)

**Pull request merged**
