### PR TITLE
selenium: Refactor WebdriverIO tests from sync to async mode

### PR DESCRIPTION
**Pull request by osamaahmed17**
Update npm package wdio-mediawiki.

Bug: T300811

### CODE REVIEW

**Comment by osamaahmed17** [comment]
@zeljkofilipin

**Comment by zeljkofilipin** [comment]
I think updating wdio-wikibase will be a multi step process.

- Make sure you have Wikibase running locally: https://www.mediawiki.org/wiki/MediaWiki-Docker/Extension/Wikibase
- Make sure you can run it's selenium tests.
- Clone wdio-wikibase on your machine.
- In Wikibase's `package.json` point wdio-wikibase to the local repository. See core for example: https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/refs/heads/master/package.json#39
- Make changes to both Wikibase and wdio-wikibase until all tests pass.
  - Wikibase tests are located in two folders. See https://www.mediawiki.org/wiki/Selenium/Reference/Example_Code
- Push Wikibase (to gerrit) and wdio-wikibase (to github) commits separately.

**Comment by zeljkofilipin** [comment]
Most of `ItemPage`, `ComponentInteraction` and `MainStatementSection` should probably be async too.

**Comment by zeljkofilipin** [comment]
I'm not sure what's the process of adding reviewers on github, so I'll add a few people that have made changes to this repository. Please add/remove reviewers as needed. cc @jakobw @chukarave @manicki

**Comment by outdooracorn** [comment]
Closing as the sync to async migration has now been completed in other PRs.

**Pull request closed without merging**
