### PR TITLE
Change !await to !(await)

### PR DESCRIPTION
**Pull request by MuhammadJaziraly**

### CODE REVIEW

**Review by jakobw — COMMENTED** [review]
The parentheses are not necessary here. Do you think they should be added for readability?

```js
( async () => {
  if ( !await Promise.resolve( false ) ) {
    console.log( 'promise resolved falsy' ); // this happens
  }
  if ( await Promise.resolve( true ) ) {
    console.log( 'promise resolved truthy' ); // this also happens
  }
} )();
```
https://runjs.co/s/q3V8UPpiY

**Comment by MuhammadJaziraly** [comment]
Thanks for the example @jakobw, I fully agree that they are not necessary, and I only added them for readability.

**Review by outdooracorn — COMMENTED** [review]
I don't feel like I need the extra parenthesis - I find I can parse the code well without them, but no big issues, so won't stop this from being merged.

**Comment by MuhammadJaziraly** [comment]
Then I feel it's not going to add that value to the code, I'll ignore it.

**Pull request closed without merging**
